package com.example.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xhf.wholeproject.model.entity.res.InfoMessageEntity;

import com.example.greendao.dao.InfoMessageEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig infoMessageEntityDaoConfig;

    private final InfoMessageEntityDao infoMessageEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        infoMessageEntityDaoConfig = daoConfigMap.get(InfoMessageEntityDao.class).clone();
        infoMessageEntityDaoConfig.initIdentityScope(type);

        infoMessageEntityDao = new InfoMessageEntityDao(infoMessageEntityDaoConfig, this);

        registerDao(InfoMessageEntity.class, infoMessageEntityDao);
    }
    
    public void clear() {
        infoMessageEntityDaoConfig.clearIdentityScope();
    }

    public InfoMessageEntityDao getInfoMessageEntityDao() {
        return infoMessageEntityDao;
    }

}
